name: my_environment
channels:
  - defaults
dependencies:
  - python=3.13.0  # Lub wersja Python, której używasz
  - dateutils=0.6.12
  - numpy=2.1.2
  - pandas=2.2.3
  - pip=24.2
  - python-dateutil=2.9.0.post0
  - pytz=2024.2
  - six=1.16.0
