json_file_path = 'D:/My/Pwr/SolVro/recrutation/Source/cocktail_dataset.json'
txt_file_path = r'D:\My\Pwr\SolVro\recrutation\Source\cocktail_dataset.txt'
id_path = 'D:/My/Pwr/SolVro/recrutation/Source/id.txt'
category_path = 'D:/My/Pwr/SolVro/recrutation/Source/category.txt'
glass_path = 'D:/My/Pwr/SolVro/recrutation/Source/glass.txt'